create or replace TRIGGER CLP_CONFIGURATION.TRG_VERSION_LOG_HIST
   AFTER DELETE
   ON CLP_CONFIGURATION.INCOMM_VERSION
   REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
BEGIN
   INSERT INTO CLP_CONFIGURATION.INCOMM_VERSION_HIST
               (BASE_VERSION , VERSION_RELEASE, VERSION_BUILD ,VERSION_DATE ,VERSION_USER ,VERSION_INS_DATE)
        VALUES (:OLD.BASE_VERSION, :OLD.VERSION_RELEASE,:OLD.VERSION_BUILD , :OLD.VERSION_DATE, :OLD.VERSION_USER,SYSDATE);
END;

/
SHOW ERROR;
