Insert into CARD (CARD_NUM_HASH,CARD_NUM_ENCR,CARD_NUM_MASK,SERIAL_NUMBER,ACCOUNT_ID,CUSTOMER_CODE,ADDRESS_ID,PRODUCT_ID,CARD_RANGE_ID,PROXY_NUMBER,CARD_STATUS,EXPIRY_DATE,
PAN_GENERATION_DATE,DATE_OF_ACTIVATION,INS_USER,INS_DATE,LAST_UPD_USER,LAST_UPD_DATE,PIN_OFF,DISP_NAME,NEXT_BILL_DATE,NEXT_MB_DATE,ISSUE_FLAG,IPIN_OFFSET,
FIRSTTIME_TOPUP,STARTERCARD_FLAG,INACTIVE_FEECALC_DATE,PRFL_CODE,PRFL_LEVL,REPL_FLAG,OLD_CARDSTAT,LAST_TXNDATE,CARDPACK_ID,CVVPLUS_REG_FLAG,CVVPLUS_ACTIVE_FLAG,
ACTIVATION_CODE,REPLACE_EXPRYDT,MERCHANT_ID,MERCHANT_NAME,STORE_ID,TERMINAL_ID,IP_ADDRESS,URL,USER_IDENTIFY_TYPE,MERCHANT_BILLABLE,REPLACE_TERMINAL_ID,
REPLACE_MERCHANT_ID,REPLACE_LOCATION_ID,BILL_ADDR,MBR_NUMB,IS_REDEEMED,LIMIT_PROFILE,FEE_PROFILE)
 values
 ('46ugZPGQMvGCjJQ8DlwAuFr/gfd/dNpVtbVV7A39HBY=','786A2BB45CB75060F5310507881D6F8C',null,'123456789',100002624,100002624,100002624,112,14,'100002599',
'PASSIVE',to_date('04-10-18','DD-MM-YY'),to_date('21-MAY-20','DD-MON-YY'),to_date('04-OCT-18','DD-MON-YY'),null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'NO','PRODUCTLEVEL','PRODUCTLEVEL');

